[package]
name = "swiss-knife"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Tool for generating, serializing (LCS), hashing and signing Diem transactions. Additionally, contains tools for testing"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
structopt = "0.3.17"
rand = "0.7.3"
hex = "0.4.2"
serde_json = "1.0.57"
serde = { version = "1.0.116", features = ["derive"] }
bcs = "0.1.2"

diem-types = { path = "../../types", version = "0.1.0" }
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
move-core-types = { path = "../../language/move-core/types", version = "0.1.0" }
transaction-builder = { path = "../../language/transaction-builder", version = "0.1.0" }
