[package]
name = "diem-json-rpc-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem JSONRPC Types"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.32"
hex = "0.4.2"
serde = { version = "1.0.116", default-features = false }
serde_json = "1.0.57"

bcs = "0.1.2"
diem-types = { path = "../../types", version = "0.0.1" }
diem-crypto = { path = "../../crypto/crypto", version = "0.0.1" }
move-core-types = { path = "../../language/move-core/types", version = "0.0.1" }
transaction-builder = { path = "../../language/transaction-builder", version = "0.1.0"}
move-explain = { path = "../../language/tools/move-explain", version = "0.1.0" }
