[package]
name = "move-core-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Core types for Move"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.32"
hex = "0.4.2"
rand = "0.7.3"
proptest = { version = "0.10.1", default-features = false, optional = true }
mirai-annotations = "1.10.1"
proptest-derive = { version = "0.2.0", default-features = false, optional = true }
ref-cast = "1.0.2"
serde = { version = "1.0.116", default-features = false }
serde_bytes = "0.11.5"
static_assertions = "1.1.0"
thiserror = "1.0.20"
once_cell = "1.4.1"

bcs = "0.1.2"
diem-crypto = { path = "../../../crypto/crypto", version = "0.1.0", default-features = false }
diem-crypto-derive = { path = "../../../crypto/crypto-derive", version = "0.1.0" }
short-hex-str = { path = "../../../common/short-hex-str", version = "0.1.0" }

[dev-dependencies]
once_cell = "1.4.1"
proptest = "0.10.1"
proptest-derive = "0.2.0"
regex = "1.3.9"
serde_json = "1.0.57"

[features]
default = ["fiat"]
fiat = ["diem-crypto/fiat"]
vanilla = ["diem-crypto/vanilla"]
fuzzing = ["proptest", "proptest-derive"]
