[package]
name = "libra-log-derive"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.41", features = ["extra-traits"] }
quote = "1.0.7"
proc-macro2 = "1.0.23"
